package aa_USER_INTERFACE_COMPONENTS.Core_UI_Classes.Trading_and_Trading_WorkFlow_Windows.Dockable.Charts.Indicators;

public abstract class MovingAverage_AbstractClass implements MovingAverage_Interface{
}
